[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
TF_CPP_MIN_LOG_LEVEL = "2"
PYTHONUNBUFFERED = "1"
